### ISSUE TITLE
Remove Banner

### ISSUE THREAD

**Issue by tamhoon** [ACTL4001-T1-2022/github-showcase-page-dka#6]
Just assigning some tasks here while we on call.

-- See if we can remove Banner? we have edited out the words so it isn't too ugly -.-

**Comment by tamhoon** [comment]
no can do.. not sure how to do it.. Any thoughts?

**Comment by dka-angela** [comment]
not sure as well. We managed to change the title so it should be ok

**Comment by tamhoon** [comment]
Hey nice! seems like you got it going... Ill just adjust the size and stuff
